- name: Configure Minikube on EC2 Instances
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker
        state: present
      become: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
      become: yes

    - name: Download kubectl
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/kubectl
        mode: '0755'
      become: yes

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
      become: yes

    - name: Start Minikube Cluster
      command: minikube start
      environment:
        HOME: "/root"
      become: yes

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f deployment.yml
      become: yes
